version: 0.0
os: linux
files:
  - source: /deploy-nestjs
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
      timeout: 3600
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ubuntu
      timeout: 3600