version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/deploy-nestjs
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
      timeout: 3600
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 3600
      runas: ubuntu