version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/deploy-nestjs
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
      timeout: 3600
  
